### PR TITLE
Merge Python3 Changes from Master into Nonblocking

### PR DESCRIPTION
**Pull request by fried**
This is an initial attempt to merge the two projects. I haven't even run the tests yet. 

But would like to gauge interest before I spend more time getting this to work. 
mysqlclient-python has waiter support, but it seems nonblocking is supported down in C, where as waiter requires no such support (as far as I can tell). I tried to keep them both

### CODE REVIEW

**Comment by fried** [comment]
I had to force this into my own branch

**Comment by fried** [comment]
Having trouble building it because of missing net_async identifiers

**Comment by chipturner** [comment]
can you figure out what went wrong with your git repo and re-send this as a non-forced merge request?  it shouldn't require forcing or anything weird, just a patch off of 83fa8b7e6c054fece6f502b31bf16572d85e588e

**Comment by fried** [comment]
Alright this is clean now

**Comment by chipturner** [comment]
now that I can view the diff, it seems to do two things -- merge in something from the pure python mysql client (waiter?) and fix py3k support.  how easy is it to separate those two apart?  ideally the py3k part could be pushed to real upstream so this branch only contains async fixes (or at least we can keep the diffs as separate commits).  this is just such a huge diff; can we shrink it to be more maintainable?

**Comment by fried** [comment]
well the changes are mysqlclient-python which will hopefully make it upstream one day
Yeah I'll pull in just the changes to master, then merge into nonblocking

**Pull request closed without merging**
